services:
  - type: web
    name: justice-org
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
