services:
  - type: web
    name: justice-org-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
    rootDir: backend
    autoDeploy: true
    envSpecificConfigs:
      nodeVersion: 20.x

  - type: static
    name: justice-org-frontend
    rootDir: frontend
    buildCommand: |
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: build
