services:
  - type: web
    name: justice-org
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm install
      npx prisma migrate deploy
      npm install --prefix ../frontend --legacy-peer-deps
      npm run build --prefix ../frontend
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
    autoDeploy: true
    envSpecificConfigs:
      nodeVersion: 20.x
